name: ssmtp-snap
base: core22
version: "2.64"
summary: Extremely simple MTA to get mail off the system to a mail hub
description: |
  sSMTP is a simple and lightweight MTA to deliver mail from a computer to a mail hub (SMTP server).

#grade: devel #This is for development only.
#confinement: devmode #This is for development only. Unconfined snap environment. For production, use strict.
grade: stable #This is for releasing in the stable channel.
confinement: strict #This is for production only.

architectures:
  - build-on: [amd64]
    build-for: [amd64]
  - build-on: [amd64, arm64]
    build-for: [arm64]
  - build-on: [amd64, armhf]
    build-for: [armhf]
  - build-on: [amd64, ppc64el]
    build-for: [ppc64el]
  - build-on: [amd64, s390x]
    build-for: [s390x]

apps:
  ssmtp:
    command: bin/ssmtp.sh
    plugs:
      - network

  config:
    command: bin/config-template.sh

  email:
    command: bin/email-template.sh

parts:
  bin:
    plugin: dump
    source: app/bin
    organize:
      ssmtp.sh: bin/ssmtp.sh
      email-template.sh: bin/email-template.sh
      config-template.sh: bin/config-template.sh

  template:
    plugin: dump
    source: app/template
    organize:
      config: template/config
      email: template/email

  ssmtp:
    plugin: nil
    stage-packages:
      - ssmtp
    stage:
      - -etc
      - -usr/share